# Generated by Django 3.0.8 on 2020-07-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billed',
        ),
    ]
