# Generated by Django 3.0.8 on 2020-07-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_billed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billed',
            options={'managed': False},
        ),
    ]
