# Generated by Django 3.0.8 on 2020-07-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20200708_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billed',
            options={},
        ),
    ]
