# Generated by Django 3.0.8 on 2020-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20200708_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed',
            name='anex_confirm',
            field=models.CharField(blank=True, db_column='Anex_Confirm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='anex_confirm_by',
            field=models.CharField(blank=True, db_column='Anex_Confirm_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='anex_confirm_dt',
            field=models.CharField(blank=True, db_column='Anex_Confirm_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit',
            field=models.CharField(blank=True, db_column='Audit', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit_by',
            field=models.CharField(blank=True, db_column='Audit_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit_dt',
            field=models.CharField(blank=True, db_column='Audit_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit_verified',
            field=models.CharField(blank=True, db_column='Audit_Verified', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit_verified_by',
            field=models.CharField(blank=True, db_column='Audit_Verified_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='audit_verified_dt',
            field=models.CharField(blank=True, db_column='Audit_Verified_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billed',
            field=models.CharField(blank=True, db_column='Billed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billed_by',
            field=models.CharField(blank=True, db_column='Billed_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billed_dt',
            field=models.CharField(blank=True, db_column='Billed_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billed_id',
            field=models.CharField(blank=True, db_column='Billed_Id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billingamount',
            field=models.CharField(blank=True, db_column='BillingAmount', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='billingnumber',
            field=models.CharField(blank=True, db_column='BillingNumber', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='bunit',
            field=models.CharField(blank=True, db_column='BUnit', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='cchanged_by',
            field=models.CharField(blank=True, db_column='CChanged_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='cchanged_dt',
            field=models.CharField(blank=True, db_column='CChanged_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='confirm_by',
            field=models.CharField(blank=True, db_column='Confirm_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='confirm_dt',
            field=models.CharField(blank=True, db_column='Confirm_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='confirm_rate',
            field=models.CharField(blank=True, db_column='Confirm_Rate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='corewt',
            field=models.CharField(blank=True, db_column='Corewt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='created_by',
            field=models.CharField(blank=True, db_column='Created_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='created_dt',
            field=models.CharField(blank=True, db_column='Created_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='cvendor_id',
            field=models.CharField(blank=True, db_column='CVendor_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='freight',
            field=models.CharField(blank=True, db_column='Freight', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='freight_val',
            field=models.CharField(blank=True, db_column='Freight_val', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='grossweight',
            field=models.CharField(blank=True, db_column='Grossweight', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billed',
            name='invoice_by',
            field=models.CharField(blank=True, db_column='Invoice_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='invoice_dt',
            field=models.CharField(blank=True, db_column='Invoice_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='invoice_no',
            field=models.CharField(blank=True, db_column='Invoice_No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='item_id',
            field=models.CharField(blank=True, db_column='Item_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='item_name',
            field=models.CharField(blank=True, db_column='Item_Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='loading',
            field=models.CharField(blank=True, db_column='Loading', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='loading_by',
            field=models.CharField(blank=True, db_column='Loading_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='loading_dt',
            field=models.CharField(blank=True, db_column='Loading_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='moveto',
            field=models.CharField(blank=True, db_column='Moveto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='mtrs',
            field=models.CharField(blank=True, db_column='Mtrs', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='mtrsrate',
            field=models.CharField(blank=True, db_column='Mtrsrate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='o_bill_date',
            field=models.CharField(blank=True, db_column='O_Bill_date', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='o_invoice_no',
            field=models.CharField(blank=True, db_column='O_Invoice_no', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='o_mtrs_rate',
            field=models.CharField(blank=True, db_column='O_Mtrs_rate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='order_id',
            field=models.CharField(blank=True, db_column='Order_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment',
            field=models.CharField(blank=True, db_column='Payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment_app',
            field=models.CharField(blank=True, db_column='Payment_App', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment_app_by',
            field=models.CharField(blank=True, db_column='Payment_App_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment_app_dt',
            field=models.CharField(blank=True, db_column='Payment_App_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment_by',
            field=models.CharField(blank=True, db_column='Payment_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='payment_dt',
            field=models.CharField(blank=True, db_column='Payment_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='rate',
            field=models.CharField(blank=True, db_column='Rate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='received',
            field=models.CharField(blank=True, db_column='Received', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='rollno',
            field=models.CharField(blank=True, db_column='Rollno', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='sales_confirm',
            field=models.CharField(blank=True, db_column='Sales_Confirm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='sales_confirm_by',
            field=models.CharField(blank=True, db_column='Sales_Confirm_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='sales_confirm_dt',
            field=models.CharField(blank=True, db_column='Sales_Confirm_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='trucknumber',
            field=models.CharField(blank=True, db_column='TruckNumber', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='updated_by',
            field=models.CharField(blank=True, db_column='Updated_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='updated_dt',
            field=models.CharField(blank=True, db_column='Updated_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vehicleno',
            field=models.CharField(blank=True, db_column='VehicleNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vehicleno_by',
            field=models.CharField(blank=True, db_column='VehicleNo_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vehicleno_dt',
            field=models.CharField(blank=True, db_column='VehicleNo_Dt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vehicleno_id',
            field=models.CharField(blank=True, db_column='VehicleNo_ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vendor_id',
            field=models.CharField(blank=True, db_column='Vendor_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='vendor_name',
            field=models.CharField(blank=True, db_column='Vendor_Name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='weight_verified',
            field=models.CharField(blank=True, db_column='Weight_Verified', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='weight_verified_by',
            field=models.CharField(blank=True, db_column='Weight_Verified_By', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed',
            name='weight_verified_dt',
            field=models.CharField(blank=True, db_column='Weight_Verified_Dt', max_length=20, null=True),
        ),
    ]
