# Generated by Django 3.0.8 on 2020-07-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20200708_1729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billed',
            table='new_bills',
        ),
    ]
