# Generated by Django 3.0.8 on 2020-07-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20200729_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billed',
            new_name='NBilled',
        ),
    ]
