# Generated by Django 3.0.8 on 2020-07-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20200729_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NBilled',
            new_name='Billed',
        ),
    ]
