# Generated by Django 3.0.8 on 2020-08-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20200729_1740'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billed',
            table='Bills',
        ),
    ]
